<!-- START PAGE CONTAINER -->
<div class="page-container page-navigation-top-fixed">
    <?php $this->load->view('layout/v_sidebar')?>
    <!-- PAGE CONTENT -->
    <div class="page-content">
        <?php $this->load->view('layout/v_vertical_menu')?>
        <?php $this->load->view('home/v_slider')?>
        <!-- PAGE CONTENT WRAPPER -->
        <div class="page-content-wrap">
            <div class="panel panel-default">
                <div class="panel-body text-justify">
                    <h2>Privacy Policy</h2>
                    <p>Perjanjian Penggunaan Layanan Situs www.plus.gaps.co.id (Perjanjian) antara Customer sebagai pengguna Situs www.plus.gaps.co.id (Customer) dan PT. Mobile Coin Asia (MCA) sebagai Pengelola Situs.  Privacy Policy memuat syarat-syarat dan ketentuan penggunaan layanan situs yang berlaku bagi Customer untuk dapat menggunakan situs www.plus.gaps.co.id. Mohon Customer untuk membaca dengan seksama Perjanjian ini, Customer harus memahami, menerima dan menyetujui semua persyaratan dan ketentuan dalam Perjanjian ini sebelum menggunakan situs dan/atau menerima konten yang terdapat di dalamnya. Dengan menggunakan dan/atau melanjutkan akses terhadap situs www.plus.gaps.co.id, Customer menyetujui persyaratan dan ketentuan MCA, dan oleh karena itu menyetujui untuk terikat dalam suatu Perjanjian dengan MCA dan oleh karenanya Customer menyatakan persetujuan untuk dapat menerima layanan dan akses atas seluruh konten yang terdapat dalam situs ini. Jika Customer tidak menerima dan menyetujui Perjanjian ini, Customer tidak diperkenankan untuk mengakses lebih lanjut situs www.plus.gaps.co.id dan dipersilahkan untuk meninggalkan situs www.plus.gaps.co.id. Setiap kegiatan terkait dengan penggunaan situs www.plus.gaps.co.id , maka baik Pengelola, Customer dan Penjual (Merchant), dilindungi secara hukum melalui Undang - Undang Republik Indonesia No.11 Tahun 2008 tentang Informasi dan Teknologi, Undang-Undang Republik Indonesia No. 19 Tahun 2002 tentang Hak Cipta, dan terhadap segala bentuk perikatan yang timbul dari segala aktifitas di situs www.plus.gaps.co.id telah memenuhi kaidah dan syarat sahnya suatu perikatan sebagaimana yang tercantum dalam Kitab Undang-Undang Hukum Perdata Indonesia.</p>

                    <h3>Ketentuan Umum</h3>
                    <ol>
                        <li>Perjanjian ini diatur dan diinterprestasikan berdasarkan Hukum Republik Indonesia (Indonesia). Pihak-pihak yang disebutkan dalam Perjanjian ini dengan ini sepakat untuk tunduk kepada pengadilan di Indonesia.</li>
                        <li>Dalam Perjanjian ini yang dimaksud dengan Customer adalah orang perseorangan, baik warga negara Indonesia, warga negara asing, maupun badan hukum dengan kemampuan menggunakan komputer, jaringan, komputer dan/atau media elektronik lainnya mampu untuk mengakses situs www.plus.gaps.co.id sesuai dengan keperluannya. Dalam hal ini termasuk juga Customer yang telah mendaftarkan diri pada situs www.plus.gaps.co.id sebagai Customer Terdaftar atau Customer tersebut membayar untuk layanan tertentu yang mungkin disediakan oleh situs www.plus.gaps.co.id.</li>
                        <li>Dengan mengakses atau menggunakan situs www.plus.gaps.co.id ini, Customer yang termasuk dalam kategori Customer sebagaimana disebutkan dalam poin 2 di atas secara sadar dan tanpa paksaan dari pihak manapun menyatakan diri setuju untuk menerima semua syarat dan ketentuan yang tercantum dalam Perjanjian ini. Sebagai Customer, Customer terikat dengan syarat dan ketentuan dalam Perjanjian yang berlaku dalam hal Customer mengakses atau menggunakan situs www.plus.gaps.co.id  ini. Jika Customer tidak menerima semua syarat dan ketentuan dalam Perjanjian ini, Customer diharuskan untuk langsung meninggalkan situs www.plus.gaps.co.id.</li>
                        <li>MCA dapat mengubah atau memperbarui Perjanjian ini setiap waktu dengan mencantumkan Perjanjian yang telah diubah atau diperbarui di dalam situs dan persyaratan dan ketentuan yang telah diubah dan diperbarui akan segera berlaku setelah persyaratan dan ketentuan yang telah diubah dan diperbarui dicantumkan oleh situs www.plus.gaps.co.id, dan Customer diwajibkan untuk setiap saat membaca persyaratan dan ketentuan baru dan dianggap telah menyetujui perubahan atau pembaruan tersebut apabila setelah dicantumkan di dalam situs www.plus.gaps.co.id dan Customer dapat  terus menggunakan situs www.plus.gaps.co.id.</li>
                        <li>Dalam situs  www.plus.gaps.co.id akan atau telah terdapat sambungan atau hyperlink (Pranala) yang terhubung situs milik pihak ketiga dan MCA dengan ini menyatakan tidak bertanggung jawab atas informasi Pranala diluar situs www.plus.gaps.co.id  atau situs yang disediakan atau dipasang oleh pihak ketiga (Isi Pihak Ketiga), baik yang dimasukkan oleh Customer yang tidak disebutkan namanya atau oleh penyedia informasi yang memperoleh pembayaran, atau bukan dibuat oleh MCA. Dengan ditampilkannya informasi Pihak Ketiga dalam situs www.plus.gaps.co.id, tidak berarti bahwa MCA maupun pihak terafiliasi, pejabat, petugas atau pegawainya menjalin hubungan kerja sebagai agen penjualan dengan pihak ketiga tersebut. Informasi Pihak Ketiga sepenuhnya merupakan tanggung jawab pihak penyedia informasi. MCA tidak menjamin bahwa semua informasi pihak ketiga akurat, tidak melanggar susila, absah atau adalah yang sesungguhnya, dan tidak bertanggungjawab jika Customer menganggap bahwa informasi pihak ketiga tersebut dapat dipercaya isinya. Selain itu MCA tidak bertanggung jawab atas kegiatan yang dilakukan oleh Customer dan tidak dapat dimintai pertanggungjawaban oleh siapa pun berkaitan dengan kerugian yang diderita pihak lain sebagai akibat perbuatan Customer.</li>
                    </ol>
                    <h3>Ketentuan Bagi Customer</h3>
                    <ol>
                        <li>Setiap Customer sepakat untuk tidak menyalin, menggunakan atau mengunduh semua informasi, tulisan, gambar, rekaman video, direktori, dokumen, database atau iklan yang ada disitus www.plus.gaps.co.id atau yang diperoleh melalui situs www.plus.gaps.co.id dengan tujuan apapun termasuk dan tidak terbatas pada diantaranya menjual kembali atau menyebarkan kembali isi situs www.plus.gaps.co.id, melakukan pemasaran massal (lewat email, SMS, surat biasa atau lainnya), menjalankan usaha untuk menyaingi situs www.plus.gaps.co.id atau memanfaatkan situs www.plus.gaps.co.id untuk keperluan komersial diluar kegiatan transaksi dengan www.plus.gaps.co.id. Customer tidak diperbolehkan mengambil isi situs www.plus.gaps.co.id secara sistematis untuk membuat atau menyusun, baik secara langsung maupun tidak langsung, koleksi, kompilasi, database atau direktori (baik menggunakan perangkat otomatis ataupun proses manual) tanpa izin tertulis dari MCA. Selain itu Customer tidak diperkenankan menggunakan isi atau bahan tersebut di atas untuk tujuan apa pun yang tidak disebutkan di dalam Perjanjian ini.</li>
                        <li>
                            Saat mengunjungi dan menggunakan situs www.plus.gaps.co.id, termasuk setiap fitur dan layanannya, Setiap Customer tidak diperkenankan untuk :
                            <ul>
                                <li>Melanggar ketentuan hukum yang berlaku (termasuk tetapi tidak terbatas pada peraturan mengenai pengawasan ekspor, perlindungan konsumen, persaingan tidak sehat, anti diskriminasi atau iklan palsu), hak - hak pihak lain baik hak intelektual, asasi, dan lainnya, dan aturan - aturan yang diatur pada Perjanjian ini.</li>
                                <li>Memberikan informasi dan informasi yang salah, tidak akurat, bersifat menyesatkan, bersifat memfitnah, bersifat asusila, mengandung pornografi, bersifat diskriminasi atau rasis.</li>
                                <li>Mengambil tindakan yang dapat mengacaukan sistem saran atau masukan dan atau peringkat (seperti menampilkan, mengimpor atau mengekspor informasi atau masukan dari situs luar atau menggunakannya untuk tujuan yang tidak terkait dengan situs www.plus.gaps.co.id).</li>
                                <li>Memberikan account di situs www.plus.gaps.co.id  (termasuk saran atau masukan) dan nama account kepada pihak lain tanpa sepengetahuan MCA.</li>
                                <li>Menyebarkan spam, hal - hal yang tidak berasusila, atau pesan elektronik yang berjumlah besar, pesan bersambung.</li>
                                <li>Menyebarkan virus atau seluruh teknologi lainnya yang sejenis yang dapat merusak dan/atau merugikan situs www.plus.gaps.co.id, afiliasinya dan Customer lainnya.</li>
                                <li>memasukkan atau memindahkan fitur pada situs www.plus.gaps.co.id tidak terkecuali tanpa sepengetahuan dan persetujuan dari MCA.</li>
                                <li>menyimpan, meniru, mengubah, atau menyebarkan konten dan fitur situs www.plus.gaps.co.id, termasuk cara pelayanan, konten,hak cipta dan intelektual yang terdapat pada Situs www.plus.gaps.co.id .</li>
                                <li>mengambil atau mengumpulkan informasi dari pengguna lain, termasuk alamat email, tanpa sepengetahuan pengguna lain.</li>
                            </ul>
                        </li>
                        <li>MCA berhak membatasi atau tidak memberikan akses, atau memberikan akses yang berbeda untuk dapat membuka situs www.plus.gaps.co.id dan fitur di dalamnya kepada masing-masing Customer,atau mengganti salah satu fitur atau memasukkan fitur baru tanpa pemberitahuan sebelumnya. Setiap Customer sadar bahwa jika situs www.plus.gaps.co.id   tidak dapat digunakan seluruhnya atau sebagian karena alasan apapun, maka usaha atau kegiatan apapun yang dilakukan Customer dapat terganggu. Setiap Customer dengan ini sepakat bahwa karena alasan apapun membebaskan MCA dari segala bentuk pertanggungjawaban terhadap Customer atau terhadap pihak ketiga jika yang bersangkutan tidak dapat menggunakan Situs www.plus.gaps.co.id  (baik karena gangguan, dibatasinya akses, dilakukannya perubahan fitur atau tidak dimasukkannya lagi fitur tertentu atau karena alasan lain); atau jika komunikasi atau transmisi tertunda, gagal atau tidak dapat berlangsung; atau jika timbul kerugian (secara langsung, tidak langsung) karena digunakannya atau tidak dapat digunakannya situs www.plus.gaps.co.id  atau salah satu fitur di dalamnya.</li>
                        <li>Dengan terus melakukan akses atau terus menggunakan situs www.plus.gaps.co.id , Customer dianggap telah membaca, memahami dan menyetujui ketentuan situs  www.plus.gaps.co.id tentang Privacy Policy yang mengatur masalah penggunaan informasi yang dimasukkan masing-masing Customer ke dalam situs www.plus.gaps.co.id. Customer menerima ketentuan ini serta tambahan atau setiap perubahan atau pembaruannya. Customer memahami dan mengetahui secara sadar bahwa MCA dapat mengubah ketentuan tentang Kerahasiaan Pribadi ini sewaktu-waktu dan akan memasukkan versi terbarunya di situs www.plus.gaps.co.id. Jika terus menggunakan situs www.plus.gaps.co.id, Customer dianggap menerima dan menyetujui ketentuan tentang Kerahasiaan Pribadi yang tercantum di situs www.plus.gaps.co.id  pada saat digunakan.</li>
                        <li>Customer mengetahui dan menyetujui bahwa harga yang tercantum pada situs www.plus.gaps.co.id dapat mengalami perubahan secara sewaktu-waktu dan tanpa pemberitahuan terlebih dahulu.</li>
                    </ol>

                    <h3>Customer Terdaftar</h3>
                    <ol>
                        <li>Dengan memilih untuk membuat akun sebagai member dari situs www.plus.gaps.co.id, Customer Terdaftar akan membuat sebuah nama akun dan PIN ketika menyelesaikan proses registrasi.</li>
                        <li>Customer Terdaftar bertanggung jawab untuk menjaga kerahasiaan dan keamanan atas nama akun dan PIN serta Customer Terdaftar bertanggung jawab sepenuhnya atas segala kegiatan yang di atasnamakan nama akun Customer Terdaftar.</li>
                        <li>Customer Terdaftar menyetujui untuk :
                            <ul>
                                <li>Segera memberitahukan kepada MCA setiap adanya dugaan penggunaan yang tidak sah/valid dengan pengatasnamaan nama akun Customer Terdaftar.</li>
                                <li>Memastikan bahwa Customer Terdaftar keluar (log out) dari akun pada setiap akhir dari aktivitas pada situs www.plus.gaps.co.id untuk menghindari kemungkinan terjadinya penyalahgunaan atas akun yang bersangkutan.</li>
                            </ul>
                        </li>
                        <li>MCA berhak sepenuhnya untuk membatasi, memblokir atau mengakhiri pelayanan dari suatu akun, melarang akses ke situs www.plus.gaps.co.id, memperlambat atau menghapus hosted content, dan mengambil langkah - langkah hukum untuk menjaga Customer Terdaftar atau Customer lain jika MCA menganggap Customer Terdaftar atau Customer lain melakukan pelanggaran hukum- hukum yang berlaku, melanggar hak milik intelektual dari pihak terkait, atau melakukan suatu pelanggaran yang melanggar hal-hal yang tertera pada Perjanjian ini.</li>
                        <li>Bahwa Customer Terdaftar tidak diperkenankan menjual, berupaya menjual, menawarkan untuk menjual, memberikan, menyerahkan atau mengalihkan Akun, Identitas Customer atau Sandi kepada pihak ketiga tanpa sepengetahuan dan persetujuan tertulis sebelumnya dari MCA. MCA dapat menangguhkan atau menghentikan Akun Customer Terdaftar atau Akun pihak yang menerima pengalihan dari Customer Terdaftar yang dijual, ditawarkan untuk dijual, diberikan, diserahkan atau dialihkan dengan melanggar ketentuan dalam Pasal ini. Apabila dengan keterbatasan kemampuan MCA dalam mengidentifikasi pelanggaran ini, maka seluruh akibat, risiko adalah merupakan tanggung jawab dari Customer Terdaftar yang mengalihkan.</li>
                    </ol>

                    <h3>Hak Dan Kewajiban Customer</h3>
                    <ol>
                        <li>Setiap Customer bertanggungjawab atas seluruh hal yang dilakukan di situs www.plus.gaps.co.id yang mengatasnamakan Customer tersebut.</li>
                        <li>Setiap Customer bertanggungjawab sepenuhnya jika Customer melakukan pelanggaran terhadap ketentuan - ketentuan yang telah dirincikan pada Perjanjian ini, dan menyetujui untuk melepaskan MCA beserta affiliasinya atas seluruh kerugian yang diakibatkan oleh pelanggaran yang dilakukan oleh Customer.</li>
                    </ol>
                    <h3>Pembatasan Tanggung Jawab MCA</h3>
                    <ol>
                        <li>Kewajiban MCA hanyalah sebatas pada penyediaan www.plus.gaps.co.id.</li>
                        <li>Barang-barang yang dijual di situs www.plus.gaps.co.id merupakan tanggung jawab sepenuhnya dari penjual yang menawarkan barang-barangnya melalui situs www.plus.gaps.co.id.</li>
                        <li>Bentuk Kerugian yang dikarenakan dari tindakan Customer  yang melanggar Perjanjian ini sepenuhnya adalah tanggung jawab Customer dimana MCA dilepaskan sepenuhnya dari tuntutan pihak-pihak yang dirugikan.</li>
                        <li>Bahwa tidak satupun dari MCA ataupun Supplier MCA, pemberi lisensi, kontraktor atau pihak-pihak lain yang terkait dalam pembuatan, produksi, atau penyampaian layanan atau konten yang terdapat dalam aplikasi ini yang diharuskan bertanggungjawab terhadap Customer ataupun setiap orang yang mengajukan klaim melalui Customer, untuk setiap kerugian atas keuntungan atau pendapatan, ketidak akuratan data, kegagalan untuk memperoleh hasil ataupun keuntungan yang diharapkan, kerugian ekonomis, insidental, signifikan, hukuman, kerugian secara tidak langsung (termasuk tetapi tidak terbatas pada biaya-biaya yang diperlukan untuk perbaikan) yang disebabkan karena akses yang Customer lakukan ataupun dikarenakan kegagalan mengakses layanan atau konten yang terdapat dalam aplikasi ini, baik berdasarkan jaminan, perjanjian, perbuatan melawan hukum, tanggung jawab produk atau teori hukum dan kemungkinan apakah MCA mengetahui ataupun tidak mengenai kemungkinan kerugian tersebut ataupun jika kemungkinan kerugian itu telah dapat diperkirakan sebelumnya. MCA tidak bertanggungjawab kepada Customer ataupun kepada pihak lainnya untuk ketidak akuratan, kesalahan, kerugian, kerusakan atau kerugian yang disebabkan baik oleh karena kegagalan, penundaan, terputusnya layanan dan konten sebagaimana terdapat pada aplikasi ini, baik seluruh ataupun sebagian. Customer menyetujui bahwa dalam setiap kejadian, Customer tidak dapat mengajukan klaim kepada MCA atas segala kerugian/kerusakan yang timbul sehubungan dengan akses terhadap layanan atau konten yang terdapat pada aplikasi ini ataupun hal lain yang timbul sehubungan dengan ketentuan dalam Perjanjian ini. Hal-hal tersebut di atas akan tetap berlaku meskipun terjadi pengakhiran terhadap Perjanjian ini ataupun telah habis jangka waktu berlakunya.</li>
                        <li>Informasi yang ditayangkan di situs www.plus.gaps.co.id disediakan tanpa ketentuan atau jaminan apapun dalam hal ketepatannya. Sejauh diijinkan oleh hukum, MCA dan para pihak ketiga yang berhubungan dengan MCA dengan ini secara tegas mengecualikan:
                            <ul>
                                <li>Semua ketentuan, jaminan dan syarat lain yang dapat dinyatakan secara tidak langsung oleh undang-undang, hukum adat atau hukum keadilan.</li>
                                <li>Kewajiban atas kehilangan atau kerugian langsung, tidak langsung atau yang merupakan akibat yang ditanggung oleh Customer dalam hubungannya dengan situs www.plus.gaps.co.id atau dalam hubungannya dengan penggunaan, ketidakmampuan menggunakan, atau akibat dari penggunaan situs www.plus.gaps.co.id, setiap situs web yang terkait dengannya dan setiap informasi yang ditempatkan padanya, termasuk, namun tidak terbatas pada, kewajiban atas:
                                    <ul>
                                        <li>kehilangan penghasilan atau pendapatan;</li>
                                        <li>kehilangan bisnis;</li>
                                        <li>kehilangan laba atau kontrak;</li>
                                        <li>kehilangan penghematan yang telahdiantisipasi sebelumnya;</li>
                                        <li>kehilangan data;</li>
                                        <li>kehilangan goodwill;</li>
                                        <li>waktu manajemen atau kantor yang tersia-siakan; dan</li>
                                        <li>kehilangan atau kerugian lain apapun jenisnya, terlepas dari bagaimana hal itu timbul dan apakah disebabkan oleh kelalaian, pelanggaran terhadap perjanjian atau lainnya, meskipun dapat diperkirakan sebelumnya. Hal ini tidak berpengaruh pada kewajiban MCA yang tidak dapat dikecualikan atau dibatasi berdasarkan hukum yang berlaku. Customer menyetujui bahwa materi yang ditayangkan di situs www.plus.gaps.co.id  adalah untuk informasi. MCA atau salah satu Pegawai MCA tidak bertanggung jawab atas akibat langsung atau tidak langsung dari keputusan Customer untuk mengajukan penawaran atau tidak mengajukan penawaran dalam situs www.plus.gaps.co.id.</li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                    </ol>
                    <h3>Hak Milik Intelektual</h3>
                    <ol>
                        <li>MCA adalah pemilik tunggal atau pemegang sah semua hak atas Situs dan Isi dalam situs www.plus.gaps.co.id. Situs www.plus.gaps.co.id  dan isinya mencakup rahasia dagang dan hak milik intelektual yang dilindungi oleh undang-undang hak cipta dan undang-undang yang melindungi kekayaan intelektual lainnya yang berlaku di seluruh dunia. Semua hak milik dan hak milik intelektual atas situs www.plus.gaps.co.id dan Isinya tetap pada MCA, afiliasinya atau pemilik lisensi Isi situs www.plus.gaps.co.id . Semua hak yang tidak dicantumkan di dalam Perjanjian ini atau oleh MCA dengan ini dilindungi undang-undang.</li>
                        <li>Situs www.plus.gaps.co.id, nama, dan ikon serta logo terkait merupakan merek dagang terdaftar di berbagai wilayah hukum dan dilindungi undang-undang tentang hak cipta, merek dagang atau hak milik kekayaan intelektual lainnya. Dilarang keras menggunakan, mengubah, menggunakan, atau memasang merek-merek tersebut di atas.</li>
                    </ol>

                    <h3>Penutup</h3>
                    <ol>
                        <li>MCA dan Customer merupakan hubungan yang tidak saling terikat dan tidak ada hubungan keagenan, kemitraan, usaha patungan, pegawai perusahaan atau pemilik waralaba-pewaralaba yang akan dibuat atau dibuat dengan adanya Perjanjian ini.</li>
                        <li>Privacy Policy ini dibuat sebagai acuan saja, dan sama sekali tidak menetapkan, membatasi, menjelaskan atau menjabarkan apa yang ada atau tercakup dalam pasal tersebut.</li>
                        <li>Tidak dilaksanakannya hak MCA untuk menuntut hak MCA berdasarkan Perjanjian ini ataupun tidak diambilnya tindakan oleh MCA terhadap pelanggaran yang dilakukan oleh Customer terhadap Perjanjian ini tidak akan mengesampingkan atau tidak mengesampingkan hak MCA untuk mengambil tindakan terhadap pelanggaran serupa atau pelanggaran berikutnya.</li>
                    </ol>
                </div>
            </div>
            <!-- END PAGE CONTENT WRAPPER -->
        </div>
        <!-- END PAGE CONTENT -->
    </div>
    <!-- END PAGE CONTAINER -->